### PR TITLE
updated to a compatible version of ring-core

### PR DESCRIPTION
**Pull request by yogthos**
Using ring-core `1.6.0` fails an assert with the following error:

```
java.lang.AssertionError: Assert failed: (every? valid-attr? attrs)
	at ring.middleware.cookies$write_attr_map.invokeStatic(cookies.clj:73) ~[na:na]
	at ring.middleware.cookies$write_attr_map.invoke(cookies.clj:73) ~[na:na]
	at ring.middleware.cookies$write_cookies$iter__34614__34618$fn__34619.invoke(cookies.clj:92) ~[na:na]
```

### CODE REVIEW

**Comment by weavejester** [comment]
Thanks! Could you change the commit message to:

    Update ring-core dependency to 1.6.2

**Comment by yogthos** [comment]
👍

**Comment by krisleech** [comment]
This is the error I've been battling with, how can I get around this until the release? Thanks.

**Comment by weavejester** [comment]
Oops, I missed the update on this PR. I've updated the Ring dependency anyway via another commit.

**Pull request closed without merging**
